Taksi/Controllers/DashboardController.cs
using System;
using System.Globalization;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Taksi.Models;
using DataAccess.SQL;
using Newtonsoft.Json;
using Taksi.Classes;

namespace Taksi.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard

        ResponseModel _rm = new ResponseModel();
        [Authorize]
        public ActionResult Index()
        {
            ViewData["payment_mode"] = PopulatePaymentModeData();
            List<DispatchPaymentMode> dipatch = new List<DispatchPaymentMode>();
            return View();
        }

        public List<DispatchPaymentMode> PopulatePaymentModeData(Dispatch dispatch = null)
       {
            var allPaymentMode = new GFleetModelContainer().PaymentModes;
            var dispatchPaymentMode = dispatch != null ? new HashSet<int>(dispatch.PaymentMode.Dispatches.Select(c => c.PaymentModeId)) : new HashSet<int>();
            var viewModel = new List<DispatchPaymentMode>();
            foreach (var paymentMode in allPaymentMode)
            {
                viewModel.Add(new DispatchPaymentMode
                {
                    PaymentModeId = paymentMode.PaymentModeId,
                    PaymentMode = paymentMode.PaymentMode1,
                    Assigned = dispatchPaymentMode.Contains(paymentMode.PaymentModeId)
                });
            }
            return viewModel;
        }

        [HttpPost]
        [Authorize]
        public ActionResult Book(string pickup, string pickupxy, string dropoff, string dropoffxy, int passengers,
           string Date, int paymentModeId, string Instruction, bool? BookingImmediate, string DeviceType, string OSVersion, string AppVersion, string BuildVersion)
        {
            ResponseModel rm;
            try
            {
                DashBoardModel saveBooking = new DashBoardModel();
                Guid bookedBy = Guid.Parse(Service.Utility.getUserId().ToString());
                DateTime DateModified = DateTime.Parse(DateTime.Now.ToString());
                int ClientId = Service.Utility.getClientId().Value;
                int OrganisationId = Service.Utility.getOrganisationId().Value;
                int CustomerId = Service.Utility.getCustomerId().Value;
                string OrgName = Service.Utility.getOrganisationName(OrganisationId);
                string BookingRequestedBy = Service.Utility.getCustomerName(User.Identity.Name);


                 rm = saveBooking.saveBooking(pickup, pickupxy, dropoff, dropoffxy, passengers, Date, bookedBy, DateModified,
                    CustomerId, ClientId, paymentModeId, Instruction, BookingRequestedBy,BookingImmediate.Value,DeviceType,OSVersion,AppVersion,BuildVersion);
            }
            catch (Exception ex)
            {
                rm = new ResponseModel() { Message = "Could not submit Data, Contact System Admin", Status = false };
            }

            return this.Json(rm);
        }

        

        [HttpPost]
        [Authorize]
        public ActionResult GetBookData()
        {
            DashBoardModel mbookdata = new DashBoardModel();
            try
            {
                mbookdata = DashBoardModel.getBookData();
                //ViewBag.BookingCount = mbookdata.OrgBookData.Count;
                var Response = Json(mbookdata);
                return Response;

            }
            catch (Exception ex)
            {
                //logToFile(ex.InnerException == null ? ex.Message : ex.InnerException.Message);
                ExceptionHandler.dbErrorLogging.LogError(ex.InnerException != null ? ex.InnerException : ex, System.Web.HttpContext.Current);

                return Json(mbookdata);
            }

        }
        [Authorize]
        public ActionResult GetApprovalData()
        {
            return View("GetApproval");
        }
        public ActionResult GetAdminData()
        {
            DashBoardModel mAdmindata = new DashBoardModel();
            try
            {
                mAdmindata = DashBoardModel.getAdminData();
                var Response = Json(mAdmindata);
                return Response;

            }
            catch (Exception ex)
            {
                //logToFile(ex.InnerException == null ? ex.Message : ex.InnerException.Message);
                ExceptionHandler.dbErrorLogging.LogError(ex.InnerException != null ? ex.InnerException : ex, System.Web.HttpContext.Current);

                return Json(mAdmindata);
            }

        }
        [Authorize]
        public JsonResult getLatestBookData(string highest)
        {
            DateTime date;
            if (DateTime.TryParse(highest, out date))
            {
                return Json(DashBoardModel.GetLatestBookData(date));
            }
            else
            {
                return Json("Wrong Date: " + highest);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult UpdateDispatchStatus(int DispatchId, int DispatchStatusId)
        {
            DashBoardModel dispatchStatus = new DashBoardModel();
            var data = dispatchStatus.UpdateDispatchStatus(DispatchId, DispatchStatusId);

            return Json(data);
        }
        
        public ActionResult UpdateRating(int DispatchId, int Rating)
        {
            DashBoardModel dispatchRating = new DashBoardModel();
            var data = dispatchRating.UpdateRating(DispatchId, Rating);

            return Json(data);
        }
        [HttpPost]
        public ActionResult Update_Booking() 
        {
            ResponseModel rm;
            rm = new ResponseModel() { Message="Data Received and is being processed"};
            return Json(rm);
        }
    }
}

Taksi/Views/Dashboard/GetApproval.cshtml
@{
    ViewBag.Title = "GetBookData";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<script src="~/js/ApprovalData.js"></script>
<script type="text/javascript">
    function first_load() {
        update_pending = true;
        var time = new Date().getTime();
        $(document.body).bind("mousemove keypress", function (e) {
            time = new Date().getTime();
        });
        function refresh() {
            if (new Date().getTime() - time >= 60000)
                window.location.reload(true);
            else
                setTimeout(refresh, 10000);
        }
        setTimeout(refresh, 10000);
        @*$.ajax({
            url: '@Url.Action("GetBookData", "Dashboard")',
            type: 'POST',
            dataType: 'JSONP', // Notice! JSONP <-- P
            success: function (json) {
                if (data != null) {
                    initial_load(data);
                    update_pending = false;
                    cache: false;
                }
                // do stuff with json (in this case an array)
                //alert("Success");
            },
            error: function () {
                alert("Error");
            },
        });*@
        $.ajax({
            url: '@Url.Action("GetBookData", "Dashboard")',
            type: 'POST',
            dataType: 'json',
            async: false,
            error: ajax_error,

            success: function (data) {
                if (data != null) {
                    initial_load(data);
                    update_pending = false;
                    //cache: false;
                }
            },
            error: ajax_error
        });
    }
</script>
<style type="text/css">

</style>
<div id="page">
    <div id="main">
        <div id="grid" class="dataTables_wrapper" role="grid">
            <table id="vehicles" class="table striped hovered dataTable mDataTable" cellspacing="0">
                <thead>
                    <tr class="mbg1">
                        <td class="RefNo" style="background-color: rgb(220, 211, 202);">
                            Ref. No
                        </td>
                        <td class="Customername" style="background-color: rgb(220, 211, 202);">
                            Customer Name
                        </td>
                        <td class="PickUpPoint" style="background-color: rgb(220, 211, 202);">
                            PickUp Point
                        </td>
                        <td class="DropOffPoint" style="background-color: rgb(220, 211, 202);">
                            DropOff Point
                        </td>
                        <td class="PickUpDateTime" style="background-color: rgb(220, 211, 202);">
                            PickUp Time
                        </td>
                        <td class="BookedDate" style="background-color: rgb(220, 211, 202);">
                            Booking Date
                        </td>
                        <td class="NoOfPassengers" style="background-color: rgb(220, 211, 202);">
                            Passengers
                        </td>
                        <td class="Status" style="background-color: rgb(220, 211, 202);">Status
                        </td>
                    </tr>
                </thead>
                <tbody class="scroll-vertical"></tbody>
            </table>
            <!--permanent scrollbar-->
        </div>
    </div>
</div>

Taksi/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
   
}
@Html.Partial("_NewBooking")
<script src="//maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=drawing&amp;key=AIzaSyDEraSXsfbkYBnkCukdi5qTKRDoIaz4WUg" type="text/javascript"></script>
@*<script src="//maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=drawing&amp;key=AIzaSyDEraSXsfbkYBnkCukdi5qTKRDoIaz4WUg" type="text/javascript"></script>*@
@*<script src="js/Jquery-ui-map/jquery.ui.map.extensions.js"></script>*@
<script src="~/Scripts/oms.min.js"></script>
<script src="~/js/map-Live.js"></script>
@Scripts.Render("~/bundles/markerlabel")

<script type="text/javascript">
    function first_load() {
        update_pending = true;
        $.ajax({
            url: '@Url.Action("GetBookData", "Dashboard")',
            type: 'POST',
            dataType: 'json',
            //error: ajax_error,
            success: function (data) {
                if (data != null) {
                    initial_load(data);
                    update_pending = false;
                }
            },
            error: ajax_error
        });
    }
</script>
<style type="text/css">
    .dataTables_scrollHeadInner
    {
        padding-left: 0px!important;
    }
</style>
<div id="page">
    <div id="main">
        <div id="mapPart">
            <div id="map">
            </div>
            <div class="grid-place">
                <span class="bookings">Bookings</span>
                <img class="pin-icon" src="" />
                <div id="grid" class="dataTables_wrapper" role="grid">
                    <table id="vehicles" class="table striped hovered dataTable mDataTable" cellspacing="0">
                        <thead>
                            <tr class="mbg1">
                                <td class="RefNo" style="background-color: rgb(220, 211, 202);">Ref. No
                                </td>
                                <td class="Customername" style="background-color: rgb(220, 211, 202);">Customer Name
                                </td>
                                <td class="PickUpPoint" style="background-color: rgb(220, 211, 202);">PickUp Point
                                </td>
                                <td class="DropOffPoint" style="background-color: rgb(220, 211, 202);">DropOff Point
                                </td>
                                <td class="PickUpDateTime" style="background-color: rgb(220, 211, 202);">PickUp Time
                                </td>
                                <td class="BookedDate" style="background-color: rgb(220, 211, 202);">Booking Date
                                </td>
                                <td class="NoOfPassengers" style="background-color: rgb(220, 211, 202);">Passengers
                                </td>
                                <td class="Status" style="background-color: rgb(220, 211, 202);">Status
                                </td>
                            </tr>
                        </thead>
                        <tbody class="scroll-vertical"></tbody>
                    </table>
                    <div>
                    </div>
                    <!--permanent scrollbar-->
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(".pin-icon").click(function () {
                var gridplace = $('.grid-place');

                if (pinned) {
                    $('body').addClass('nojQuery');
                    gridplace.removeClass('noHover');
                    $(".pin-icon").attr("src", "../../img/pin.png");
                    $(".pin-icon").attr("title", "pin to page");

                } else {
                    $('body').removeClass('nojQuery');
                    gridplace.addClass('noHover');
                    $(".pin-icon").attr("src", "../../img/unpin.png");
                    $(".pin-icon").attr("title", "Unpin from page");
                }

                pinned = !pinned;
            });
        </script>

        <!-- ployzones -->
        <div id="zones" class="sidewindow">
            <h1>Polyzones</h1>
            <a class="close"></a>
            <div id="zones-list">
            </div>
            <div id="zones-group">
            </div>
            <div id="zones-details">
                <div class="line">
                    <fieldset>
                        <div class="line">
                            <label for="Isgeofencespeed">
                                Is GeoFenceSpeed?
                            </label>
                            <input type="checkbox" id="zones-Isgeofencespeed" />
                        </div>
                    </fieldset>
                </div>
                <div class="line">
                    <fieldset>
                        <div class="line">
                            <label for="zones-name">
                                Name
                            </label>
                            <input id="zones-name" />
                        </div>
                        <div class="line">
                            <label for="zones-geofenceactive">
                                Geofence Active?
                            </label>
                            <input type="checkbox" id="zones-geofenceactive" name="zonesgeofenceactive" />
                        </div>
                    </fieldset>
                </div>
                <div id="zone-frequency">
                    <div class="line">
                        <fieldset>
                            <legend>Exit Repoting</legend>
                            <div class="line">
                                <label for="zones-reportonexit">
                                    Report on Exit?
                                </label>
                                <input type="checkbox" id="zones-reportonexit" name="zonesreportonexit" />
                            </div>
                            <div class="line">
                                <label for="zones-reportonexitfreq">
                                    Frequency (Minutes)
                                </label>
                                <input id="zones-reportonexitfreq" />
                            </div>
                            <div class="line">
                                <label for="zones-reportonexitnoofalerts">
                                    No of Alerts
                                </label>
                                <input id="zones-reportonexitnoofalerts" />
                            </div>
                        </fieldset>
                    </div>
                    <div class="line">
                        <fieldset>
                            <legend>Entry Repoting</legend>
                            <div class="line">
                                <label for="zones-reportonentry">
                                    Report on Entry?
                                </label>
                                <input type="checkbox" id="zones-reportonentry" name="zonesreportonentry" />
                            </div>
                            <div class="line">
                                <label for="zones-reportonentryfreq">
                                    Frequency (Minutes)
                                </label>
                                <input id="zones-reportonentryfreq" />
                            </div>
                            <div class="line">
                                <label for="zones-reportonentrynoofalerts">
                                    No of Alerts
                                </label>
                                <input id="zones-reportonentrynoofalerts" />
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div id="zone-speed" style="display: none">
                    <fieldset>
                        <div class="line">
                            <label for="zones-Speed">
                                Speed
                            </label>
                            <input id="zones-Speed" />
                        </div>
                    </fieldset>
                </div>
                <fieldset title='Use "," or ";" to split your email accounts/phone numbers.
                        Example: test@example.com,info@example.com; or 254723456789;25434567987'>
                    <div class="line">
                        <label for="zones-phone">
                            Phone(s)
                        </label>
                        <input id="zones-phone" />
                    </div>
                    <div class="line">
                        <label for="zones-email">
                            Email(s)
                        </label>
                        <input id="zones-email" />
                    </div>
                </fieldset>
                <fieldset>
                    <div class="line">
                        <div id="zones-create" class="button">
                            Create
                        </div>
                        <div id="zones-show" class="button">
                            Show
                        </div>
                    </div>
                    <div class="line">
                        <div id="zones-save" class="button">
                            Save
                        </div>
                        <div id="zones-del" class="button">
                            Delete
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div id="zone-creator" class="sidewindow">
            <h1>Create zone</h1>
            <a class="close"></a>
            <p>
            </p>
            <div class="line">
                <div id="zone-creator-finish" class="button">
                    Finish
                </div>
            </div>
        </div>
    </div>
</div>