GFleetV3/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GFleetV3.Models;
using DataAccess.SQL;
using System.Threading;
namespace GFleetV3.Controllers
{
    public class GroupController : Controller
    {
        
        //
        // GET: /Group/

        [Authorize]
        [Authorization]
        public ActionResult Index(int page = 1, string sort = "Reg", string sortDir = "ASC", string dataGrid = "false")
        {
            Boolean isDatagrid;
            if (Boolean.TryParse(dataGrid, out isDatagrid))
            {
                if (isDatagrid)
                {
                    return PartialView("_GroupGrid", gridData(page, ref sort, ref sortDir));
                }
            }
            var data = gridData(page, ref sort, ref sortDir);
            return View(data);
        }

        private PagedGroupModel gridData(int page, ref string sort, ref string sortDir)
        {
            ModelGroup groupModel = new ModelGroup();
            const int pageSize = 100;
            var totalRows = groupModel.CountGroup();

            sortDir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? sortDir : "asc";

            sort = "GroupId";

            var group = groupModel.GetGroupPage(page, pageSize, "it." + sort + " " + sortDir);

            var data = new PagedGroupModel()
            {
                TotalRows = totalRows,
                PageSize = pageSize,
                Group = group
            };
            return data;
        }

        //
        // GET: /Group/Create

        [Authorize]
        [Authorization]
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                ViewBag.IsUpdate = false;
                return View("_Group");
            }
            else
            {
                return View("_Group");
            }
        }

        //
        // POST: /Group/Create

        [HttpPost]

        [Authorize]
     //   [Authorization]
        public ActionResult createEditGroup(Group mGroup, string Command)
        {
            ModelGroup groupModel = new ModelGroup();
            if (!ModelState.IsValid)
            {
                ErrorModel errMod = new ErrorModel();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errMod.Errors.Add(error.ErrorMessage);
                    }
                }
                return View("_Error", errMod);
            }
            else if (Command == "Save")
            {
                mGroup.ClientId = Service.Utility.getClientId().Value;
                mGroup.ModifiedBy = Guid.Parse(Service.Utility.getUserId().ToString());
                mGroup.DateModified = DateTime.Parse(DateTime.Now.ToString());
                ResponseModel rm = groupModel.CreateGroup(mGroup);
                return this.Json(rm);
            }

            else if (Command == "Update")
            {
                mGroup.ClientId = Service.Utility.getClientId().Value;
                mGroup.ModifiedBy = Guid.Parse(Service.Utility.getUserId().ToString());
                mGroup.DateModified = DateTime.Parse(DateTime.Now.ToString());
                return this.Json(groupModel.UpdateGroup(mGroup));
            }

            ErrorModel errModX = new ErrorModel();
            errModX.Errors.Add("Unrecognized operation, kindly refresh browser and retry.");
            return View("_Error", errModX);
        }
        //
        // GET: /Group/Edit/5

        [Authorize]
        [Authorization]
        public ActionResult Edit(int id)
        {
            ModelGroup groupModel = new ModelGroup();
            var data = groupModel.GetGroup(id);
            if (Request.IsAjaxRequest())
            {
                ViewBag.IsUpdate = true;
            }
            return View("_Group", data);
        }

        //
        // GET: /Group/Delete/5

        [Authorize]
        [Authorization]
        public ActionResult Delete(int id)
        {
            return View();
        }
    }
}

GFleetV3/Views/Group/Index.cshtml
@model GFleetV3.Models.PagedGroupModel
@{
    ViewBag.Title = "Taksi";

    if (false)
    {
    <script src="../../Scripts/jquery-1.7.1-vsdoc.js" type="text/javascript"></script>
    }
    
}
@*<script src="../../Scripts/GfleetScripts.js" type="text/javascript"></script>*@
<script type="text/javascript">
    $(document).ready(function () {
        $("#CreateGroup").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            loadDialog(url, 'dialog-edit', 'Create Group');
            return false;
        });

        $(".editDialog").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            loadDialog(url, 'dialog-edit', 'Edit Group');
            return false;
        });

        $(".confirmDialog").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');

            $("#dialog-confirm").dialog({
                autoOpen: false,
                resizable: false,
                height: 170,
                width: 350,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                        window.location = url;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });
            $("#dialog-confirm").dialog('open');
            return false;
        });

        $(".viewDialog").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            $("#dialog-view").dialog({
                title: 'View Group',
                position: [300, 100],
                autoOpen: false,
                resizable: false,
                width: 'auto',
                autoResize: true,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                dialogClass: "fixed-dialog",
                open: function (event, ui) {
                    $(this).load(url);
                },
                buttons: {
                    "Close": function () {
                        $(this).dialog('close');
                    }
                }
            });

            $("#dialog-view").dialog('open');
            return false;
        });

        $("#btncancel").live("click", function (e) {
            location.reload(true);
            //$("#dialog-edit").dialog('close');

        });
    });
</script>
<table width="961"  border="0" align="center" cellpadding="0">
    <tr>
        <td height="42" colspan="2" class="td1" align="right">
        </td>
    </tr>
    <tr>
        <td width="208" height="169" class="td1" valign="top">
            @Html.Partial("_sidebarmenu", GFleetV3.Models.SideMenu.getSubmenu(@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()))            

        </td>
        <td width="747" class="td1" valign="top">
            <div id="add-Item">
                @Html.ActionLink(" ", "Create", "Group", null, new { @id = "CreateGroup", @class = "add-Group" })
            </div>
            @Html.Partial("_GroupGrid", Model)
        </td>
    </tr>
</table>
<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete ?
    </p>
</div>
<div id="dialog-edit" style="width: auto; height: auto;">
</div>
<div id="dialog-view" style="display: none">
</div>

GFleetV3/Views/Group/_Group.cshtml
@model DataAccess.SQL.Group
@{  
    Layout = null;
    if (false)
    {
    <script src="../../Scripts/jquery-1.7.1-vsdoc.js" type="text/javascript"></script>

    }
}
@using (Html.BeginForm("CreateEditGroup", "Group", FormMethod.Post))
{  <div id="wait" style="display: none;">
    </div>
    <div class="divautosize">
        @Html.ValidationSummary(true)
        <div id="from_result">
        </div>
        @if (ViewBag.IsUpdate == true)
        { 
            @Html.HiddenFor(model => model.GroupId)
            @Html.Hidden("isEditing", true)
        }
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(model => model.GroupName)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.GroupName)
            </div>
            <div class="validation-msg">
                @Html.ValidationMessageFor(model => model.GroupName)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Active)
            </div>
            <div class="editor-field">
                @Html.CheckBoxFor(model => model.Active)
            </div>
            <div class="validation-msg">
                @Html.ValidationMessageFor(model => model.Active)
            </div>
        </fieldset>
        <br />
        <div>
            @if (ViewBag.IsUpdate == true)
            { 

                <button type="submit" id="btnUpdate" name="Command" value="Update" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                    <span class="ui-button-text">Update</span></button>
            }
            else
            { 
                <button type="submit" id="btnSave" name="Command" value="Save" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                    <span class="ui-button-text">Save</span></button>
            }
            <button type="button" id="btncancel" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                <span class="ui-button-text">Cancel</span></button>
            &nbsp; &nbsp;
        </div>
    </div>
}
<script type="text/javascript">
    $(function () {
        dialogStartUp(displayResult);
    });
    function displayResult(data) {
        console.log(data);
        data = data.Data;
        var table = document.getElementById("gridData");
        var rowCount = table.rows.length;
        var row = table.insertRow(rowCount);
        row.className = rowCount % 2 == 0 ? "data_even" : "data_odd";

        var driverlicencetype = row.insertCell(0);
        var action = row.insertCell(1);

        driverlicencetype.innerHTML = data.DriverLicenceType; driverlicencetype.className = "data_cell";
        var element1 = document.createElement("label");
        var a = document.createElement('a');
        var linkText = document.createTextNode("Edit");
        a.appendChild(linkText);
        a.setAttribute("class", "editDialog");
        a.title = "Edit";
        a.href = "/DriverLicenceType/Edit/" + data.Id;
        element1.appendChild(a);
        action.appendChild(element1); action.className = "data_cell";
    }
</script>

GFleetV3/Views/Group/_GroupGrid.cshtml
@model GFleetV3.Models.PagedGroupModel
@{
    Layout = null;
    WebGrid grid = new WebGrid(rowsPerPage: Model.PageSize);
    grid.Bind(Model.Group,
              autoSortAndPage: false,
              rowCount: Model.TotalRows
              );
    if (false)
    {
    <script src="../../Scripts/jquery-1.7.1-vsdoc.js" type="text/javascript"></script>
    }
}
@grid.GetHtml(
               htmlAttributes: new { id = "gridData" },
            fillEmptyRows: false,
            tableStyle: "qlabs_grid_container",//"webgrid",
            headerStyle: "header_row",//"webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "data_even",//"webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "data_odd", //"webgrid-row-style",
            mode: WebGridPagerModes.All,
                    firstText: "<< First",
                    previousText: "< Prev",
                    nextText: "Next >",
                    lastText: "Last >>",
    columns: new[] {
        
        grid.Column("GroupName",style: "data_cell", 
                    header: "Group Name"),        
        grid.Column("Active",style: "data_cell", 
                    header: "Active"),
        grid.Column("",style: "data_cell", 
                    header: "Actions",
                    format: @<text>
<label>@Html.ActionLink("Edit", "Edit", new { id = item.GroupId }, new { @class = "editDialog"/*, data_dialog_id = "edit-Dialog"*/ })</label>
@*|
@Html.ActionLink("Delete", "Delete", new { id = item.InsuaranceTypeId }, new { @class = "confirmDialog" })*@
</text>
        )
})
<script type="text/javascript">
    InitGrid('gridData');
</script>