GFleetV3/Controllers/DriverEndorsementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GFleetV3.Models;
using DataAccess.SQL;

namespace GFleetV3.Controllers
{
    public class DriverEndorsementController : Controller
    {
        //
        // GET: /DriverEndorsement/


        [Authorize]
        [Authorization]
        public ActionResult Index(int page = 1, string sort = "Reg", string sortDir = "ASC", string dataGrid = "false")
        {
            Boolean isDatagrid;
            if (Boolean.TryParse(dataGrid, out isDatagrid))
            {
                if (isDatagrid)
                {
                    return PartialView("_DriverEndorsementGrid", gridData(page, ref sort, ref sortDir));
                }
            }
            var data = gridData(page, ref sort, ref sortDir);
            return View(data);
        }

        private PagedDriverEndorsmentModel gridData(int page, ref string sort, ref string sortDir)
        {
            ModelDriverEndorsment driverEndorsmentModel = new ModelDriverEndorsment();
            const int pageSize = 100;
            var totalRows = driverEndorsmentModel.CountDriverEndorsment();

            sortDir = sortDir.Equals("desc", StringComparison.CurrentCultureIgnoreCase) ? sortDir : "asc";

            //var validColumns = new[] { "custid", "name", "address", "contactno" };
            //if (!validColumns.Any(c => c.Equals(sort, StringComparison.CurrentCultureIgnoreCase)))
            sort = "Id";

            var driverEndorsment = driverEndorsmentModel.GetDriverEndorsmentPage(page, pageSize, "it." + sort + " " + sortDir);

            var data = new PagedDriverEndorsmentModel()
            {
                TotalRows = totalRows,
                PageSize = pageSize,
                DriverEndorsment = driverEndorsment
            };
            return data;
        }


        //
        // GET: /DriverEndorsement/Create
        [Authorize]
        [Authorization]
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                PopulateDriverDropDownList();
                ViewBag.IsUpdate = false;
                return View("_DriverEndorsement");
            }
            else
            {
                PopulateDriverDropDownList();
                return View("_DriverEndorsement");
            }
        }

        //
        // POST: /DriverEndorsement/Create

        [HttpPost]
        [Authorize]
      //  [Authorization]
        public ActionResult CreateEditDriverEndorsement(DriverEndosment mDriverEndorsement, string Command)
        {
            ModelDriverEndorsment driverEndorsmentModel = new ModelDriverEndorsment();
            if (!ModelState.IsValid)
            {
                ErrorModel errMod = new ErrorModel();
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        errMod.Errors.Add(error.ErrorMessage);
                    }
                }
                return View("_Error", errMod);
            }
            else if (Command == "Save")
            {
                mDriverEndorsement.ModifiedBy = Guid.Parse(Service.Utility.getUserId().ToString());

                ResponseModel rm = driverEndorsmentModel.CreateDriverEndosment(mDriverEndorsement);
                return this.Json(rm);
            }

            else if (Command == "Update")
            {
                return this.Json(driverEndorsmentModel.UpdateDriverEndosment(mDriverEndorsement));
            }

            return Content("Unrecognized operation, kindly refresh browser and retry.");
        }

        //
        // GET: /DriverEndorsement/Edit/5

        [Authorize]
        [Authorization]
        public ActionResult Edit(int id)
        {
            ModelDriverEndorsment driverEndorsmentModel = new ModelDriverEndorsment();
            PopulateDriverDropDownList();
            var data = driverEndorsmentModel.GetDriverEndorsment(id);
            if (Request.IsAjaxRequest())
            {
                ViewBag.IsUpdate = true;
                return View("_DriverEndorsement", data);
            }
            else

                return View(data);
        }
        //
        // POST: /DriverEndorsement/Edit/5


        //
        // GET: /DriverEndorsement/Delete/5
        [Authorize]
        [Authorization]
        public ActionResult Delete(int id)
        {
            return View();
        }
        private void PopulateDriverDropDownList(object Driver = null)
        {
            var DriverQuery = from d in new GFleetModelContainer().People.OfType<Driver>()
                              orderby d.FirstName
                              select d;
            ViewBag.Driver = new SelectList(DriverQuery, "PersonId", "FirstName", Driver);
        }
    }
}

GFleetV3/Views/DriverEndorsement/Index.cshtml
@model GFleetV3.Models.PagedDriverEndorsmentModel
@{
    ViewBag.Title = "Taksi";

    if (false)
    {
    <script src="../../Scripts/jquery-1.7.1-vsdoc.js" type="text/javascript"></script>
    }
}
@*<script src="../../Scripts/GfleetScripts.js" type="text/javascript"></script>*@
<script type="text/javascript">
    $(document).ready(function () {
        $("#CreateDriverEndorsment").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            loadDialog(url, 'dialog-edit', 'Driver Endorsment');
            return false;
        });

        $(".editDialog").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            loadDialog(url, 'dialog-edit', 'Edit Driver Endorsment');
            return false;
        });

        $(".confirmDialog").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');

            $("#dialog-confirm").dialog({
                autoOpen: false,
                resizable: false,
                height: 170,
                width: 350,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                        window.location = url;
                    },
                    "Cancel": function () {
                        $(this).dialog("close");
                    }
                }
            });
            $("#dialog-confirm").dialog('open');
            return false;
        });

        $(".viewDialog").live("click", function (e) {
            // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            $("#dialog-view").dialog({
                title: 'View Driver Endorsment',
                position: [300, 100],
                autoOpen: false,
                resizable: false,
                width: 'auto',
                autoResize: true,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                dialogClass: "fixed-dialog",
                open: function (event, ui) {
                    $(this).load(url);
                },
                buttons: {
                    "Close": function () {
                        $(this).dialog('close');
                    }
                }
            });

            $("#dialog-view").dialog('open');
            return false;
        });

        $("#btncancel").live("click", function (e) {
            location.reload(true);
            //$("#dialog-edit").dialog('close');

        });
    });
</script>
<div>
    <div id="sidemenucontent">
        @*@Html.Partial("_sidebarmenu", GFleet.Models.SideMenu.getSubmenu("Driver"))*@
        @Html.Partial("_sidebarmenu", GFleetV3.Models.SideMenu.getSubmenu(@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()))

    </div>
    <div id="bodycontent">
        @Html.ActionLink("Driver Endorsment", "Create", "DriverEndorsement", null, new { @id = "CreateDriverEndorsment" })
        <br />
        <div id="dataGrid">
            @Html.Partial("_DriverEndorsementGrid", Model)
        </div>
    </div>
</div>
<div id="dialog-confirm" style="display: none">
    <p>
        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
        Are you sure to delete ?
    </p>
</div>
<div id="dialog-edit" style="width: auto; height: auto;">
</div>
<div id="dialog-view" style="display: none">
</div>

GFleetV3/Views/DriverEndorsement/_DriverEndorsement.cshtml
@model DataAccess.SQL.DriverEndosment
@{  
    Layout = null;
    if (false)
    {
    <script src="../../Scripts/jquery-1.7.1-vsdoc.js" type="text/javascript"></script>
    }
}
@using (Html.BeginForm("CreateEditDriverEndorsement", "DriverEndorsement", FormMethod.Post))
{  <div id="wait" style="display: none;">
    </div>
    <div class="divautosize">
        @Html.ValidationSummary(true)
        <div id="from_result">
        </div>
        @if (ViewBag.IsUpdate == true)
        { 
            @Html.HiddenFor(model => model.Id)
            @Html.Hidden("isEditing", true)
        }
        <fieldset>
            <div class="editor-label">
                @Html.LabelFor(model => model.PersonId)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.PersonId, new SelectList(ViewBag.Driver, "Value", "Text"), new { style = "width:210px;padding: 5px;border: 1px solid #CCC;" })
            </div>
            <div class="validation-msg">
                @Html.ValidationMessageFor(model => model.PersonId)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Endosment)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Endosment)
            </div>
            <div class="validation-msg">
                @Html.ValidationMessageFor(model => model.Endosment)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Like)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Like)
            </div>
            <div class="validation-msg">
                @Html.ValidationMessageFor(model => model.Like)
            </div>
        </fieldset>
        <br />
        <div style="bottom: 0px; position: absolute;">
            @if (ViewBag.IsUpdate == true)
            { 

                <button type="submit" id="btnUpdate" name="Command" value="Update" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                    <span class="ui-button-text">Update</span></button>
            }
            else
            { 
                <button type="submit" id="btnSave" name="Command" value="Save" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                    <span class="ui-button-text">Save</span></button>
            }
            <button type="button" id="btncancel" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">
                <span class="ui-button-text">Cancel</span></button>
            &nbsp; &nbsp;
        </div>
    </div>
}
<script type="text/javascript">
    $(function () {
        dialogStartUp();
    });
</script>

GFleetV3/Views/DriverEndorsement/_DriverEndorsementGrid.cshtml
@model GFleetV3.Models.PagedDriverEndorsmentModel
@{
    Layout = null;
    WebGrid grid = new WebGrid(rowsPerPage: Model.PageSize);
    grid.Bind(Model.DriverEndorsment,
              autoSortAndPage: false,
              rowCount: Model.TotalRows
              );
    if (false)
    {
    <script src="../../Scripts/jquery-1.7.1-vsdoc.js" type="text/javascript"></script>
    }
}
@grid.GetHtml(
    fillEmptyRows: false,
    alternatingRowStyle: "alternate-row",
    headerStyle: "grid-header",
    footerStyle: "grid-footer",
    mode: WebGridPagerModes.All,
            firstText: "<< First",
            previousText: "< Prev",
            nextText: "Next >",
            lastText: "Last >>",
    columns: new[] {
        
        grid.Column("Person.FirstName", 
                    header: "Driver"),
        grid.Column("Endosment", 
                    header: "Endorsement"),
        grid.Column("Like", 
                    header: "Like"),
        grid.Column("", 
                    header: "Actions",
                    format: @<text>
@Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "editDialog"/*, data_dialog_id = "edit-Dialog"*/ })
@*|
@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "confirmDialog" })*@
</text>
        )
})