Taksi/Controllers/ReportAnalysisController.cs
using DataAccess.SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Taksi.Models;

namespace Taksi.Controllers
{
    public class ReportAnalysisController : Controller 
    {
            // GET: ReportAnalysis/Create
            [Authorize]
            //[Authorization]
            public ActionResult Create()
            {
                PopulateVehicleDropDownList();
                PopulateOrganisationDropDownList();
                PopulateCustomerDropDownList();
                PopulateDriverDropDownList();
                PopulateSMSStatusDropDownList();
                PopulatePassengerOnBoardDropDownList();
                PopulateCallBackDropDownList();
                return PartialView("_ReportAnalysis");
            }
            [Authorize]
            //[Authorization]
            public ActionResult GenerateReport(DispatchRptParam mReportParam)
            {
                return View("ReportControls", ReportAnalysis.GetDispatchRpt(mReportParam));

            }

            [Authorize]
            //[Authorization]
            public ActionResult export(string reportType, string StartDate, string EndDate, string OrganisationId,
                string CustomerId, string VehicleId, bool IsDispactchedChk, bool IsNotDispactchedChk, string SmsStatusId, string PassengerOnBoardId, string CallBackId)
            {
                DateTime sdate;
                DateTime edate;
                if (!validateReportInput(StartDate, EndDate, out  sdate, out  edate))
                {
                    return View();
                }
                string spacer = " " + Environment.NewLine + " ";

                List<object> data = new List<object>();
                List<vw_DispatchReport> values = ReportAnalysis.GetDispatchRptDownload(sdate, edate, OrganisationId,CustomerId, VehicleId, IsDispactchedChk, IsNotDispactchedChk, SmsStatusId, PassengerOnBoardId, CallBackId);
                data.AddRange(values.Select(m => new
                {
                    Date = m.DateModified,
                    Organization = m.OrganisationName,
                    Customer = m.CustomerName,
                    Vehicle = m.VehicleRegCode,
                    From = m.PickUpPointName,
                    To = m.DropOffPointName,
                    Driver = m.DriverName,
                    DispatchStatus = m.DispatchStatus,
                    POBStatus = m.POBStatus,
                    CallBackName = m.CallBackName,
                    MsgStatus = m.Status,
                    SMS = m.CustomerSMS
                }));

                return new ExportResult<object>
                (
                    ControllerContext,
                    "Dispatch report (" + sdate.ToString() + ") - (" + edate.ToString() + ")",
                    data,
                    reportType
                );
            }

            private Boolean validateReportInput(string StartDate, string EndDate, out DateTime sdate, out DateTime edate)
            {
                sdate = DateTime.Now;
                edate = DateTime.Now;


                EndDate = HttpUtility.UrlDecode(EndDate);     //endDate = endDate.Replace("+", ""); 
                StartDate = HttpUtility.UrlDecode(StartDate);   //startDate = startDate.Replace("+", "");

                //validate start date
                if (string.IsNullOrEmpty(StartDate))
                {
                    ViewBag.message = "A start date must be selected!!";
                    return false;
                }
                if (!DateTime.TryParse(StartDate, out sdate))
                {
                    string fdate = StartDate;
                    string otherDate = fdate.Substring(3, 3) + fdate.Substring(0, 3) + fdate.Substring(6, 4)
                        + (fdate.Length > 10 ? fdate.Substring(11, fdate.Length - 11) : "");
                    if (!DateTime.TryParse(otherDate, out sdate))
                    {
                        ViewBag.message = "Invalid start date specified!!";
                        return false;
                    }
                }
                StartDate = sdate.ToString("dd/MM/yyyy HH:mm:ss");

                //validate end date
                if (string.IsNullOrEmpty(EndDate))
                {
                    ViewBag.message = "An end date must be selected!!";
                    return false;
                }
                if (!DateTime.TryParse(EndDate, out edate))
                {
                    string fdate = EndDate;
                    string otherDate = fdate.Substring(3, 3) + fdate.Substring(0, 3) + fdate.Substring(6, 4)
                        + (fdate.Length > 10 ? fdate.Substring(11, fdate.Length - 11) : " 23:59:59.999");
                    if (!DateTime.TryParse(otherDate, out edate))
                    {
                        ViewBag.message = "Invalid start date specified!!";
                        return false;
                    }
                }
                //edate = edate.Add(TimeSpan.FromDays(1)).AddMilliseconds(-1);

                return true;
            }

            private void PopulateVehicleDropDownList(object Vehicle = null)
            {
                int ClientId = Service.Utility.getClientId().Value;
                var VehicleQuery = from d in new GFleetModelContainer().ClientVehicles.Where(v => v.ClientId == ClientId)
                                   orderby d.Vehicle.RegistrationNo
                                   select new { VehicleId = d.VehicleId, RegistrationNo = (d.Vehicle.RegistrationNo + " (" + d.Vehicle.NickName + ")") };
                ViewBag.Vehicle = new SelectList(VehicleQuery, "VehicleId", "RegistrationNo", Vehicle);
            }

            private void PopulateOrganisationDropDownList(object Organisation = null)
            {
                int ClientId = Service.Utility.getClientId().Value;
                var OrganisationQuery = from d in new GFleetModelContainer().Organisations.Where(v => v.ClientId == ClientId)
                                        orderby d.OrganisationName
                                        select d;
                ViewBag.Organisation = new SelectList(OrganisationQuery, "OrganisationId", "OrganisationName", Organisation);
            }

            private void PopulateCustomerDropDownList(object Customer = null)
            {
                int ClientId = Service.Utility.getClientId().Value;
                var CustomerQuery = from d in new GFleetModelContainer().People.OfType<Customer>().Where(v => v.ClientId == ClientId)
                                    orderby d.FirstName
                                    select new { PersonId = d.PersonId, Name = d.FirstName + d.LastName };
                ViewBag.Customer = new SelectList(CustomerQuery, "PersonId", "Name", Customer);
            }

            private void PopulateDriverDropDownList(object Driver = null)
            {
                int ClientId = Service.Utility.getClientId().Value;
                var DriverQuery = from d in new GFleetModelContainer().People.OfType<Driver>().Where(v => v.ClientId == ClientId)
                                  orderby d.FirstName
                                  select new { PersonId = d.PersonId, Name = d.DriverNameNumber };
                ViewBag.Driver = new SelectList(DriverQuery, "PersonId", "Name", Driver);
            }

            private void PopulatePassengerOnBoardDropDownList(object POBStatus = null)
            {
                var PassengerOnBoardQuery = from d in new GFleetModelContainer().PassengerOnBoards
                                            orderby d.POBStatus
                                            select new { PassengerOnBoardId = d.PassengerOnBoardId, POBStatus = d.POBStatus };
                ViewBag.PassengerOnBoard = new SelectList(PassengerOnBoardQuery, "PassengerOnBoardId", "POBStatus", POBStatus);
            }

            private void PopulateCallBackDropDownList(object CallBack = null)
            {
                var CallBackQuery = from d in new GFleetModelContainer().CallBacks
                                    orderby d.CallBackName
                                    select new { CallBackId = d.CallBackId, CallBack = d.CallBackName };
                ViewBag.CallBack = new SelectList(CallBackQuery, "CallBackId", "CallBack", CallBack);
            }

            private void PopulateSMSStatusDropDownList(object SmsStatus = null)
            {

                var SmsStatusQuery = from d in new GFleetModelContainer().vw_SmsStatus
                                     orderby d.Status
                                     select d;
                ViewBag.SmsStatus = new SelectList(SmsStatusQuery, "StatusId", "Status", SmsStatus);
            }
    }
}

Taksi/Views/ReportAnalysis/ReportControls.cshtml
@model List<DataAccess.SQL.vw_DispatchReport>

@{
    Layout = null;
    int cnt = 0;
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
    <meta name="viewport" content="width=device-width" />
    <title>Dispatch Report</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatable")
    @Styles.Render("~/Content/Reports/reports.css")
    <link href="~/Content/Reports/TableTools.css" rel="stylesheet" />
    <script type="text/javascript">
        var the_dataTable;
        $(document).ready(function () {

            function div() { return $(document.createElement('div')); }
            var smstodisplay = 'sms';
            var $element = div().addClass('element');
            $("trrr").not(':first').hover(
              function () {
                  div().addClass('subelement')
                  .hide()
                  .html('SSSS')
                  .attr('title', smstodisplay)
                  .appendTo($element)
                  .hover(function () { $(this).addClass('route_hover'); },
                         function () { $(this).removeClass('route_hover'); })
              },

              function () {
                  $(this).css("background", "");
              }
            );

            $("#btnXLS").click(function (e) {
                post("xls");
            });
            $("#btnCSV").click(function (e) {
                post("csv");
            });
            $("#btnDOC").click(function (e) {
                post("DOC");
            });
            $("#btnXML").click(function (e) {
                post("xml");
            });
            $("#btnHTML").click(function (e) {
                post("html");
            });
            $("#btnPDF").click(function (e) {
                post("pdf");
            });

            $.urlParam = function (name) {
                var results = new RegExp('[\\?&]' + name + '=([^&#]*)', 'gi').exec(window.location.href);
                return results[1] || 0;
            }
            loadDataTable();
        });

        function post(reportType) {
            var params = $.param({
                reportType: reportType,
                StartDate: $.urlParam('StartDate'),
                //StartTime: $.urlParam('StartTime'),
                EndDate: $.urlParam('EndDate'),
                //EndTime: $.urlParam('EndTime'),
                IsDispactchedChk: $.urlParam('IsDispactchedChk'),
                IsNotDispactchedChk: $.urlParam('IsNotDispactchedChk'),
                OrganisationId: $.urlParam('OrganisationId'),
                CustomerId: $.urlParam('CustomerId'),
                VehicleId: $.urlParam('VehicleId'),
                SmsStatusId: $.urlParam('SmsStatusId')
            });
            window.open('../export/?' + params);
        }


        function loadDataTable() {
            //if (vehicles.length > 0) {
            if (the_dataTable == null) {
                the_dataTable = $('#tblDispatch').DataTable({
                    "oTableTools": {
                        "sSwfPath": "../../Scripts/dataTable/copy_csv_xls_pdf.swf",
                        "aButtons": [
                            {
                                "sExtends": "copy"
                                , "mColumns": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
                            },
                            {
                                "sExtends": "csv"
                                , "mColumns": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
                                , "fnClick": function (nButton, oConfig, oFlash) {
                                    //alert('Mouse click');
                                    this.fnSetText(oFlash, exportMyTable(oConfig, this, childRows));
                                    //this.fnSetText(oFlash, this.fnGetTableData(oConfig));
                                    //console.log(oConfig);
                                }
                            },
                            {
                                "sExtends": "pdf"
                                , "mColumns": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13]
                            },
                            {
                                "sExtends": "print"
                                , "mColumns": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
                            },

                        ]
                    },
                    "scrollCollapse": true,
                    "paging": false,
                    "ordering": true,
                    "order": [[0, "desc"]],
                    "info": false,
                    "ScrollY": "350px",
                    "bPaginate": false,
                    //"sDom": 'Tlfrtip'

                    "sDom": '<"top_left"l><"top_right"Tf>'
                });
            }
        }
        function ajax_error(request, text, error) {
            console.log(request);
            console.log(text);
            console.log(error);
        }
    </script>
    <style>
        .subelement {
            display: none;
            width: 129px;
            height: 1.2em;
            padding-left: 10px;
            overflow: hidden;
            font-weight: normal;
            cursor: pointer;
        }

        .route_hover {
            background: #ddf;
        }

        .cancellation {
            background: #FF0000;
        }

        .disregard {
            background: #996633;
        }

        div.DTTT_container {
            margin-top: 5px;
            margin-left: 5px;
        }

        .dataTables_filter {
            margin-top: 5px;
            float: right;
            position: relative;
        }
    </style>
</head>
<body>
    <div id="popup">
        @*<div class="btnsbar">
                <button id="btnExportToExcel" value="xls">
                    To Excel</button>
                <button type="button" value="xls" id="btnXLS" class=" x-btn-text icon-pagewhiteexcel">
                    XLS</button>
                <button type="button" value="csv" id="btnCSV" class=" x-btn-text icon-pageattach">
                    CSV</button>
                <button type="button" value="doc" id="btnDOC" class=" x-btn-text icon-pagewhiteword">
                    DOC</button>
                <button type="button" value="xml" id="btnXML" class=" x-btn-text icon-pagewhitecode">
                    XML</button>
                <button type="button" value="html" id="btnHTML" class=" x-btn-text icon-pagewhiteh">
                    HTML</button>
                <button type="button" value="pdf" id="btnPDF" class=" x-btn-text icon-pagewhiteacrobat">
                    PDF</button>
            </div>
            <div id="header1">
                <h1>&nbsp;</h1>
                <div id="time-and-date">
                </div>
                <div id="description">
                </div>
            </div>*@
        <div id="reportdata">
            <div class="day" id="">
                <h2 class="headerday" id="h">Dispatch Report</h2>
                <table cellpadding="0" id="tblDispatch" class="tabledata">
                    <thead>
                        <tr>
                            <th>
                                Ref No.
                            </th>
                            <th>
                                Date
                            </th>
                            <th>
                                Organization
                            </th>
                            <th>
                                Customer
                            </th>
                            <th>
                                Dispatched Status
                            </th>
                            <th>
                                Dispatched By
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="@((cnt++ % 2 == 0 ? "even" : "odd") + (@item.POBStatus=="Cancellation"? " cancellation":"") + (@item.POBStatus=="Disregard"? " disregard":"") )" title="@item.CustomerSMS">
                                <td>
                                    @item.DispatchId
                            </td>
                            <td>
                                @item.DateModified
                        </td>
                        <td>
                            @item.OrganisationName
                    </td>
                    <td>
                        @item.CustomerName
                </td>
              <td>
                @item.Status
            </td>
         <td>
            @item.DispatchUser
       </td>
     </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

Taksi/Views/ReportAnalysis/_ReportAnalysis.cshtml
@model Taksi.Models.DispatchRptParam
<script>
    $(document).ready(function () {
        report_initialise();

        $("#cmbVehicle").searchable({
            //maxListSize: 100,                       // if list size are less than maxListSize, show them all
            //maxMultiMatch: 50,                      // how many matching entries should be displayed
            //exactMatch: false,                      // Exact matching on search
            wildcards: true,                        // Support for wildcard characters (*, ?)
            ignoreCase: true,                       // Ignore case sensitivity
            //latency: 200,                           // how many millis to wait until starting search
            warnMultiMatch: 'top {0} matches ...',  // string to append to a list of entries cut short by maxMultiMatch
            warnNoMatch: 'no matches ...',          // string to show in the list when no entries match
            zIndex: 'auto'                          // zIndex for elements generated by this plugin
        });
    });
    function report_initialise() {
        $('#reports .close').click(closeAll);
        //$('#report-create').click(report_create);
        $('#report-from').datepicker({ defaultDate: -7 }).datepicker('setDate', -7);
        $('#report-to').datepicker().datepicker('setDate', new Date());
        $('#report-from-time').timePicker();
        $('#report-to-time').timePicker();
        $('#report-from-time').val('00:00');
        $('#report-to-time').val('23:59');
    }
    function report_create() {
        if (typeof selected_vehicle == 'undefined' || selected_vehicle == null) {
            return alert('No vehicle selected');
        }

        var type = $('#report-type').val();
        var format = $('#report-format').val();
        var from = $('#report-from').datepicker('getDate');
        var to = $('#report-to').datepicker('getDate');

        var period = days_between(from, to);
        var max = type == 'detail' ? detail_max_period :
                  type == 'travel' ? travel_max_period : stop_max_period;

        if (period > max) {
            return alert('The maximum period for this report type is ' + max + ' days');
        }

        from = $('#report-from').datepicker('getDate');
        to = $('#report-to').datepicker('getDate');
        $.datepicker.formatDate('yyyy-mm-dd', from);
        $.datepicker.formatDate('yyyy-mm-dd', to);

        var fdate = from.getFullYear() + ' - ' + (from.getMonth() + 1) + ' - ' + from.getDate();
        var tdate = to.getFullYear() + ' - ' + (to.getMonth() + 1) + ' - ' + to.getDate();
        fdate = fdate + ' ' + $('#report-from-time').val();
        tdate = tdate + ' ' + $('#report-to-time').val();

        //console.log(fdate);
        //console.log(tdate);

        var params = $.param({
            type: $('#report-type').val(),
            //format: $('#report-format').val().replace(/ /g, ""),
            startDate: fdate,
            endDate: tdate,
            regNo: selected_vehicle.Reg
        });

        window.open('Create/?' + params,
                    'win',
                    'toolbar=1,scrollbars=1,location=0,statusbar=1,' +
                    'menubar=1,resizable=1,left=20,top=20,' +
                    'width=' + ($(window).width() - 40) + ',' +
                    'height=' + ($(window).height() - 20));
    }
</script>
<style>
    #report-from, #report-to {
        width: 100px;
        text-align: center;
    }


    #report-from-time, #report-to-time {
        width: 33px;
        text-align: center;
        margin-right: 3px;
        margin-left: 3px;
    }

    #report-format {
        width: 164px;
    }

    #reports {
        padding: 8px;
    }

    .sidewindow .label {
        width: 55px;
        height: 18px;
        float: left;
        padding: 2px 0 0 0;
    }

    input[type=checkbox] {
        max-width: 20px;
        max-width: 20px;
    }

    .line {
        text-align: left;
    }

    .checkbox {
        padding-top: 7px;
        margin-top: 0;
        margin-bottom: 0;
    }

    .button {
        width: 5em;
        float: right;
        margin: .1em;
        padding: 0 .2em;
        background: url("../Content/images/btn.bmp") repeat;
        border: 1px solid #666;
        font-size: 80%;
        text-align: center;
        line-height: 1.8;
        cursor: pointer;
    }

    #report-create {
        font-size: 105%;
        color: black;
    }

    input, .button, .sidewindow, .sidewindow h1, .sidewindow .close {
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
    }

    fieldset {
        border: 1px solid #ddd;
        -webkit-border-radius: 8px;
        -moz-border-radius: 8px;
        border-radius: 8px;
    }

    .fieldsetdispatchparam {
        margin-bottom: 15px;
        margin-top: 15px;
    }

    .form-control {
        display: block;
        width: 100%;
        margin-bottom: 10px;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.428571429;
        color: #555555;
        vertical-align: middle;
        background-color: #ffffff;
        border: 1px solid #cccccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        -webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
        transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
    }

    fieldset legend {
        text-align: left;
    }
</style>
@using (Html.BeginForm("GenerateReport", "ReportAnalysis", FormMethod.Post))
{
    <div id="reports" class="sidewindow">
        <a class="close"></a>
        <div class="line">
            <div class="label">
                From
            </div>
            @Html.TextBoxFor(model => model.StartDate, "{0:d}", new { id = "report-from", placeholder = "Start Date" })
            @Html.TextBoxFor(model => model.StartTime, "{0:t}", new { id = "report-from-time", placeholder = "StartTime", @class = "reporthrsmin" })
        </div>
        <div class="line">
            <div class="label">
                To
            </div>

            @Html.TextBoxFor(model => model.EndDate, "{0:d}", new { id = "report-to", placeholder = "End Date" })
            @Html.TextBoxFor(model => model.EndTime, "{0:t}", new { id = "report-to-time", placeholder = "EndTime", @class = "reporthrsmin" })
        </div>
        <fieldset class="fieldsetdispatchparam">
            <legend>Report Criteria</legend>
            @Html.EditorFor(model => model.Dispactched, "DispatchStatus")

            @Html.DropDownListFor(model => model.DriverUserId, new SelectList(ViewBag.Driver, "Value", "Text"), "All Drivers", new { id = "cmbDriver", title = "Please Select Driver", @class = "form-control" })

            @Html.DropDownListFor(model => model.OrganisationId, new SelectList(ViewBag.Organisation, "Value", "Text"), "All Organisations", new { id = "cmbOrganisation", title = "Please Select Organisation", @class = "form-control" })

            @Html.DropDownListFor(model => model.CustomerId, new SelectList(ViewBag.Customer, "Value", "Text"), "All Customers", new { id = "cmbCustomer", title = "Please Select Customer", @class = "form-control" })

            @Html.DropDownListFor(model => model.VehicleId, new SelectList(ViewBag.Vehicle, "Value", "Text"), "All Vehicles", new { id = "cmbVehicle", title = "Please Select Vehicle", @class = "form-control" })

            @Html.DropDownListFor(model => model.SmsStatusId, new SelectList(ViewBag.SmsStatus, "Value", "Text"), "All Sms Status", new { id = "cmbSmsStatus", title = "Please Select Sms Status", @class = "form-control" })

            @Html.DropDownListFor(model => model.PasserngerOnBoardId, new SelectList(ViewBag.PassengerOnBoard, "Value", "Text"), "All P.O.B Status", new { id = "cmbPOBStatus", title = "Please Select P.O.B Status", @class = "form-control" })

            @Html.DropDownListFor(model => model.CallBackId, new SelectList(ViewBag.CallBack, "Value", "Text"), "All Call Back", new { id = "cmbCallBack", title = "Please Select Call Back", @class = "form-control" })
        </fieldset>
        <button type="submit" id="report-create" name="Command" class="button" value="Book">
            <span class="ui-button-text">Create</span>
        </button>
    </div>
}
<script type="text/javascript">

    $(function () {
        dialogdispatch();
    });

    function dialogdispatch() {
        $('form').submit(function () {
            window.open('/ReportAnalysis/Create/?' + $(this).serialize(), 'win',
                'toolbar=1,scrollbars=1,location=0,statusbar=1,' +
                'menubar=1,resizable=1,left=20,top=20,' +
                'width=' + ($(window).width() - 40) + ',' +
                'height=' + ($(window).height() - 20));
            return false;
        });

        $("form button[type=submit]").click(function () {
            $("button[type=submit]", $(this).parents("form")).removeAttr("clicked");
            $(this).attr("clicked", "true");
        });
    }

    function dispatchreport_open(content) {
        var panel;
        if ($('#JsDispatchPanelRptId').length < 1) {
            panel = $('body').jsPanel
                ({
                    title: '',
                    size: 'auto',
                    //overflow:'scroll',
                    controls: { buttons: 'closeonly' },
                    position: { top: 100, right: 100 },
                    resizable: false,
                    content: content,
                    id: 'JsDispatchPanelRptId',
                    selector: '#event-onjspanelclosed',
                    modal: false
                });
            $('body').on('onjspanelclosed', function (event, id) {
                if (id == "JsDispatchPanelRptId") {
                    //alert( event.type + ' observed on element id: ' + id );
                }
            });
        } else {

        }

    }

    function load_dispatchcontent(link, id) {
        $.get(link, function (data) {
            dispatchreport_open(data);
        });
    }
    </script>